# Generated by Django 5.2.7 on 2025-10-16 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('grade_level', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('learning_focus', models.CharField(choices=[('Math', 'Math'), ('English', 'English'), ('Both', 'Both')], max_length=10)),
                ('lesson_style', models.CharField(choices=[('Voice', 'Voice'), ('Mixed', 'Mixed')], max_length=10)),
                ('session_duration', models.IntegerField(choices=[(10, '10'), (15, '15'), (20, '20')])),
                ('learning_goal', models.TextField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('Match lessons to age and grade', 'Match lessons to age and grade'), ('Choose tone and vocabulary', 'Choose tone and vocabulary'), ('Create focused sessions', 'Create focused sessions'), ('Personalize time and style', 'Personalize time and style')], max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
