# Generated by Django 4.2.25 on 2025-11-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_country_customuser_timezone_childprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='learning_focus',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='learning_goal',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='lesson_style',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='session_duration',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='age',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
