# Generated by Django 4.2.25 on 2025-11-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_childprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
